server:
  port: 8081
  servlet:
    encoding:
      enable: true
      charset: UTF-8
      force: true

spring:
  application:
    name: SAA-01HelloWorld
  ai:
    dashscope:
      api-key: ${aliQwen-api}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: qwen3-max
